server:
  port: 10010

spring:
  application:
    name: gateway

  cloud:
    nacos:
      server-addr: 121.41.107.144:8848



    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true  #这个配置是设置在URL请求是项目名称的字母使用小写，默认是大写
      routes:
        - id: travel-service
          uri: lb://travelservice
          predicates:
            - Path=/travel/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - StripPrefix=1
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址，lb即loadbalance负载均衡
          predicates:
            - Path=/user/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - StripPrefix=1