server:
  port: 10010

spring:
  application:
    name: gateway

  cloud:
    nacos:
      server-addr: 121.41.107.144:8848

    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址，lb即loadbalance负载均衡
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: travel-service
          uri: lb://travelservice
          predicates:
            - Path=/**