server:
  port: 8081

spring:
  application:
    name: userservice

  cloud:
    nacos:
      server-addr: 116.62.134.8:8848

  main:
    banner-mode: off

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://47.98.138.0:3306/userservice?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: userservice
    password: 2x8R3WmbCzt6tcEd
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

  # 邮箱服务
  mail:
    host: smtp.126.com
    username: z1042155850@126.com
    password: JIVBRTVHJNWAPAWU
    #username: songyanglei177@126.com
    #password: MTEOLFKTJDFFMGJC
    default-encoding: UTF-8
  thymeleaf:
    prefix: classpath:/static/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix: .html
    mode: HTML5

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      # 配置逻辑删除，只在mybatisPlus时候生效
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false



